---
title: "analisis_pib_pais"
author: "MariaFernanda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library ( datos)
library(dplyr)
library(ggplot2)

```

Obtener la tabla descendente con pib per capita para los paises del continente americas en el año 2007
```{r cars}
paises <- datos::paises


paises_americas_2007 <- paises |> 
  filter(continente == "Américas" & anio == 2007) |> 
  select(pais, pib_per_capita) |> 
  arrange(desc(pib_per_capita))

```


```{r pressure, echo=FALSE}
plot(pressure)
```

Grafico de barras que represente el pib per capita por pais
```{r}
paises_americas_2007 |> 
  ggplot(aes(x = pais, y = pib_per_capita)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "PIB per cápita por país (2007)",
       x = "Paises",
       y = "PIB per cápita") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
